# Generated by Django 4.2.4 on 2023-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/static/images/')),
                ('title', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('beds', models.CharField(max_length=10)),
                ('baths', models.CharField(max_length=5)),
                ('garages', models.CharField(max_length=5)),
                ('category', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageSrc', models.ImageField(upload_to='media/static/images/')),
                ('title', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Picnic', 'Picnic')], default='Travel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageSrc', models.ImageField(upload_to='media/static/images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
    ]
