# Generated by Django 4.2.4 on 2023-09-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_rename_image_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraphLong',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraphShort',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='news',
            name='quote',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
